### ISSUE TITLE
Native Rust implementation

### ISSUE THREAD

**Issue by dtolnay** [m-ou-se/ryu-rust#1]
Just filing an issue to track this note I saw in the readme:

> In the future, this crate might be replaced by a native Rust implementation.

I did a line-by-line port from C to unsafe Rust in https://github.com/dtolnay/ryu which may or may not be useful as a starting point for you if you eventually decide to pursue a Rust implementation.

**Comment by m-ou-se** [comment]
Nice! I can also make you owner of https://crates.io/crates/ryu, so you can replace the crate by yours, if you want.

**Comment by StyMaar** [comment]
There's also a safe rust implementation now : https://github.com/peter-bertok/float_fast_print

**Comment by dtolnay** [comment]
@m-ou-se thanks! I am not ready to take over the name just yet, but at some point if I decide to start using that code in serde_json it would be lovely to have the recognizable crate name. I would first need to contribute a change upstream which implements a more human-readable format, e.g. printing `0.3` rather than the current `3E-1`. Will keep you posted.

@StyMaar when I tried them in https://github.com/dtolnay/dtoa/commit/3097ce397ce5db669db4ffd61140d5f277050f06, my implementation was 5-15% faster than the C implementation provided by this crate (which I haven't looked into, but may have to do with the safe `F64String` wrapper layer in this repo rather than the upstream C code), while the safe rust one was 10-50% slower than the C implementation. If they can make up the performance difference that would be great -- for serde_json's purposes the presence of unsafe code is not a factor and we would go with whatever is the fastest pure Rust implementation.

```
test bench_c_ryu::bench_e_f32                ... bench:          30 ns/iter (+/- 0)
test bench_c_ryu::bench_e_f64                ... bench:          41 ns/iter (+/- 1)
test bench_c_ryu::bench_max_f32              ... bench:          30 ns/iter (+/- 0)
test bench_c_ryu::bench_max_f64              ... bench:          40 ns/iter (+/- 0)
test bench_c_ryu::bench_short_f32            ... bench:          34 ns/iter (+/- 0)
test bench_c_ryu::bench_short_f64            ... bench:          59 ns/iter (+/- 1)

test bench_dtolnay_ryu::bench_e_f32          ... bench:          26 ns/iter (+/- 0)
test bench_dtolnay_ryu::bench_e_f64          ... bench:          37 ns/iter (+/- 0)
test bench_dtolnay_ryu::bench_max_f32        ... bench:          25 ns/iter (+/- 0)
test bench_dtolnay_ryu::bench_max_f64        ... bench:          38 ns/iter (+/- 1)
test bench_dtolnay_ryu::bench_short_f32      ... bench:          30 ns/iter (+/- 0)
test bench_dtolnay_ryu::bench_short_f64      ... bench:          57 ns/iter (+/- 1)

test bench_float_fast_print::bench_e_f32     ... bench:          33 ns/iter (+/- 0)
test bench_float_fast_print::bench_e_f64     ... bench:          56 ns/iter (+/- 0)
test bench_float_fast_print::bench_max_f32   ... bench:          33 ns/iter (+/- 0)
test bench_float_fast_print::bench_max_f64   ... bench:          59 ns/iter (+/- 1)
test bench_float_fast_print::bench_short_f32 ... bench:          35 ns/iter (+/- 0)
test bench_float_fast_print::bench_short_f64 ... bench:          63 ns/iter (+/- 0)
```

@peter-bertok

**Comment by dtolnay** [comment]
@m-ou-se I believe I have something that is worth publishing as `ryu`. Take a look and let me know what you think.

- [readme](https://github.com/dtolnay/ryu/blob/master/README.md#ry%C5%AB-)
- [rustdoc](https://dtolnay.github.io/ryu/ryu/index.html)

I pushed updated benchmarks to https://github.com/dtolnay/dtoa/commit/b63a8d379ffac0f2915fef3e7a302f17744e1975. You can run them locally by running `cargo bench` against that commit. My implementation is 10-15% faster than this crate, 15-40% faster than `float_fast_print`, and 20-50% faster than `dtoa`.

```
test bench_c_ryu::bench_e_f32                ... bench:          30 ns/iter (+/- 0)
test bench_c_ryu::bench_e_f64                ... bench:          39 ns/iter (+/- 1)
test bench_c_ryu::bench_max_f32              ... bench:          30 ns/iter (+/- 0)
test bench_c_ryu::bench_max_f64              ... bench:          38 ns/iter (+/- 2)
test bench_c_ryu::bench_short_f32            ... bench:          33 ns/iter (+/- 1)
test bench_c_ryu::bench_short_f64            ... bench:          59 ns/iter (+/- 2)

test bench_dtoa::bench_e_f32                 ... bench:          49 ns/iter (+/- 1)
test bench_dtoa::bench_e_f64                 ... bench:          65 ns/iter (+/- 2)
test bench_dtoa::bench_max_f32               ... bench:          49 ns/iter (+/- 3)
test bench_dtoa::bench_max_f64               ... bench:          73 ns/iter (+/- 4)
test bench_dtoa::bench_short_f32             ... bench:          40 ns/iter (+/- 1)
test bench_dtoa::bench_short_f64             ... bench:          48 ns/iter (+/- 3)

test bench_dtolnay_ryu::bench_e_f32          ... bench:          25 ns/iter (+/- 1)
test bench_dtolnay_ryu::bench_e_f64          ... bench:          36 ns/iter (+/- 2)
test bench_dtolnay_ryu::bench_max_f32        ... bench:          25 ns/iter (+/- 0)
test bench_dtolnay_ryu::bench_max_f64        ... bench:          37 ns/iter (+/- 2)
test bench_dtolnay_ryu::bench_short_f32      ... bench:          28 ns/iter (+/- 0)
test bench_dtolnay_ryu::bench_short_f64      ... bench:          55 ns/iter (+/- 3)

test bench_float_fast_print::bench_e_f32     ... bench:          32 ns/iter (+/- 0)
test bench_float_fast_print::bench_e_f64     ... bench:          56 ns/iter (+/- 4)
test bench_float_fast_print::bench_max_f32   ... bench:          33 ns/iter (+/- 0)
test bench_float_fast_print::bench_max_f64   ... bench:          59 ns/iter (+/- 1)
test bench_float_fast_print::bench_short_f32 ... bench:          35 ns/iter (+/- 1)
test bench_float_fast_print::bench_short_f64 ... bench:          61 ns/iter (+/- 3)
```

**Comment by m-ou-se** [comment]
@dtolnay Looks great! Sent you an invite for the crate ownership.
